[package]
name = "libhelloworld"
description = "This is where I make a project."
authors = ["AzureDiamond"]

[target]
lib = true
sources = ["src/**.cpp", "src/**.cc", "src/**.c"]
headers = ["src/**.hpp", "src/**.h"]

[dependencies]
